export const SCENARIOS = {
  WALK_IN: "walk-in",
  MEMBER: "member",
  BOOKING_CUSTOMER: "booking-customer",
  HOSTED_GUEST: "hosted-guest",
  EVENT_ATTENDEE: "event-attendee",
  UNPAID_CHECKOUT: "unpaid-checkout",
  STOCK_CATALOG: "stock-catalog",
  CLEANING_QUEUE: "cleaning-queue",
  MAINTENANCE_TICKET: "maintenance-ticket",
} as const;

export const UI_STATES = {
  EMPTY: "empty",
  BUSY: "busy",
  OVERDUE: "overdue",
  BLOCKED: "blocked",
  APPROVAL_REQUIRED: "approval-required",
  PAY_LATER: "pay-later",
  COMPLIMENTARY: "complimentary",
  HOSTED_GUEST: "hosted-guest",
  EVENT_ATTENDEE: "event-attendee",
  CLEANING: "cleaning",
  MAINTENANCE: "maintenance",
  SHIFT_DISCREPANCY: "shift-discrepancy",
} as const;

const NOW = new Date();
const TODAY_START = new Date(NOW.getFullYear(), NOW.getMonth(), NOW.getDate());

function hoursFromBase(h: number): Date {
  return new Date(TODAY_START.getTime() + h * 3_600_000);
}

function daysFromBase(d: number, h = 0): Date {
  return new Date(TODAY_START.getTime() + d * 86_400_000 + h * 3_600_000);
}

export const BRANCHES = [
  {
    id: "seed-branch-main",
    name: "Downtown Hub",
    timezone: "Africa/Cairo",
    currency: "EGP",
  },
  {
    id: "seed-branch-secondary",
    name: "Maadi Workspace",
    timezone: "Africa/Cairo",
    currency: "EGP",
  },
];

export const FLOORS = [
  { id: "seed-floor-ground", branchId: "seed-branch-main", name: "Ground Floor", sortOrder: 0 },
  { id: "seed-floor-first", branchId: "seed-branch-main", name: "First Floor", sortOrder: 1 },
  { id: "seed-floor-second", branchId: "seed-branch-secondary", name: "Main Floor", sortOrder: 0 },
];

export const SPACES = [
  {
    id: "seed-space-desk-1",
    branchId: "seed-branch-main",
    floorId: "seed-floor-ground",
    name: "Desk A1",
    kind: "desk",
    capacity: 1,
    status: "occupied" as const,
  },
  {
    id: "seed-space-desk-2",
    branchId: "seed-branch-main",
    floorId: "seed-floor-ground",
    name: "Desk A2",
    kind: "desk",
    capacity: 1,
    status: "occupied" as const,
  },
  {
    id: "seed-space-desk-3",
    branchId: "seed-branch-main",
    floorId: "seed-floor-ground",
    name: "Desk A3",
    kind: "desk",
    capacity: 1,
    status: "available" as const,
  },
  {
    id: "seed-space-desk-4",
    branchId: "seed-branch-main",
    floorId: "seed-floor-first",
    name: "Desk B1",
    kind: "desk",
    capacity: 1,
    status: "available" as const,
  },
  {
    id: "seed-space-desk-5",
    branchId: "seed-branch-main",
    floorId: "seed-floor-first",
    name: "Desk B2",
    kind: "desk",
    capacity: 1,
    status: "reserved" as const,
  },
  {
    id: "seed-space-meeting-room",
    branchId: "seed-branch-main",
    floorId: "seed-floor-first",
    name: "Meeting Room Alpha",
    kind: "meeting_room",
    capacity: 6,
    status: "occupied" as const,
  },
  {
    id: "seed-space-private-office",
    branchId: "seed-branch-main",
    floorId: "seed-floor-first",
    name: "Private Office 1",
    kind: "private_office",
    capacity: 3,
    status: "cleaning" as const,
  },
  {
    id: "seed-space-event-area",
    branchId: "seed-branch-main",
    floorId: "seed-floor-ground",
    name: "Event Space",
    kind: "event_area",
    capacity: 30,
    status: "occupied" as const,
  },
  {
    id: "seed-space-blocked-desk",
    branchId: "seed-branch-main",
    floorId: "seed-floor-ground",
    name: "Desk C1 (Blocked)",
    kind: "desk",
    capacity: 1,
    status: "blocked" as const,
  },
  {
    id: "seed-space-maintenance-room",
    branchId: "seed-branch-main",
    floorId: "seed-floor-second",
    name: "Storage Room",
    kind: "private_office",
    capacity: 2,
    status: "maintenance" as const,
  },
];

export const PEOPLE = [
  {
    id: "seed-person-walkin",
    displayName: "Ahmed Farouk",
    phone: "01000000001",
    email: "ahmed.farouk@example.com",
    notes: "Walk-in customer - first visit",
  },
  {
    id: "seed-person-member",
    displayName: "Sara Mahmoud",
    phone: "01000000002",
    email: "sara.mahmoud@example.com",
    notes: "Active monthly member",
  },
  {
    id: "seed-person-booking",
    displayName: "Mohamed Ali",
    phone: "01000000003",
    email: "mohamed.ali@example.com",
    notes: "Meeting room booker",
  },
  {
    id: "seed-person-host",
    displayName: "Nadia Hassan",
    phone: "01000000004",
    email: "nadia.hassan@example.com",
    notes: "Tenant / host account owner",
  },
  {
    id: "seed-person-guest",
    displayName: "Karim Youssef",
    phone: "01000000005",
    email: "karim.youssef@example.com",
    notes: "Hosted guest",
  },
  {
    id: "seed-person-attendee",
    displayName: "Laila Ibrahim",
    phone: "01000000006",
    email: "laila.ibrahim@example.com",
    notes: "Event attendee",
  },
  {
    id: "seed-person-cashier",
    displayName: "Omar El-Sayed",
    phone: "01000000007",
    email: "omar.elsayed@example.com",
    notes: "Staff - cashier",
  },
  {
    id: "seed-person-manager",
    displayName: "Heba Ahmed",
    phone: "01000000008",
    email: "heba.ahmed@example.com",
    notes: "Staff - manager",
  },
];

export const CUSTOMER_ACCOUNTS = [
  {
    id: "seed-account-host",
    branchId: "seed-branch-main",
    name: "Nadia Hassan Consulting",
    accountType: "business",
    billingEmail: "billing@nadia-consulting.com",
  },
  {
    id: "seed-account-walkin",
    branchId: "seed-branch-main",
    name: "Ahmed Farouk",
    accountType: "individual",
  },
];

export const TENANTS = [
  {
    id: "seed-tenant-host",
    accountId: "seed-account-host",
    branchId: "seed-branch-main",
    name: "Nadia Hassan Consulting",
    status: "active",
    guestPolicy: "host_bills_all",
  },
];

export const PLANS = [
  {
    id: "seed-plan-basic",
    branchId: "seed-branch-main",
    name: "Basic Hot Desk",
    includedMinutes: 3000,
    priceCents: 150000,
    currency: "EGP",
  },
  {
    id: "seed-plan-premium",
    branchId: "seed-branch-main",
    name: "Premium Desk",
    includedMinutes: 12_000,
    priceCents: 350000,
    currency: "EGP",
  },
];

export const MEMBERSHIPS = [
  {
    id: "seed-membership-active",
    personId: "seed-person-member",
    planId: "seed-plan-basic",
    status: "active",
    startsAt: daysFromBase(-60),
    endsAt: daysFromBase(30),
  },
];

export const BOOKINGS = [
  {
    id: "seed-booking-confirmed",
    personId: "seed-person-booking",
    spaceId: "seed-space-desk-5",
    status: "confirmed" as const,
    startsAt: daysFromBase(1, 9),
    endsAt: daysFromBase(1, 17),
    depositCents: 0,
    currency: "EGP",
    notes: "Full day desk booking",
  },
  {
    id: "seed-booking-checkedin",
    personId: "seed-person-booking",
    spaceId: "seed-space-meeting-room",
    status: "checked_in" as const,
    startsAt: TODAY_START,
    endsAt: hoursFromBase(4),
    depositCents: 50000,
    currency: "EGP",
    notes: "Team meeting",
  },
  {
    id: "seed-booking-cancelled",
    personId: "seed-person-booking",
    spaceId: null,
    status: "cancelled" as const,
    startsAt: daysFromBase(-3, 10),
    endsAt: daysFromBase(-3, 12),
    depositCents: 0,
    currency: "EGP",
    notes: "Cancelled by customer",
  },
  {
    id: "seed-booking-noshow",
    personId: "seed-person-walkin",
    spaceId: null,
    status: "no_show" as const,
    startsAt: daysFromBase(-1, 14),
    endsAt: daysFromBase(-1, 16),
    depositCents: 0,
    currency: "EGP",
  },
];

export const VISITS = [
  {
    id: "seed-visit-walkin",
    branchId: "seed-branch-main",
    personId: "seed-person-walkin",
    visitType: "walk_in" as const,
    billingResponsibility: "visitor" as const,
    status: "active" as const,
    bookingId: null,
    membershipId: null,
    hostAccountId: null,
    checkedInAt: hoursFromBase(-1),
    checkedOutAt: null,
  },
  {
    id: "seed-visit-member",
    branchId: "seed-branch-main",
    personId: "seed-person-member",
    visitType: "member" as const,
    billingResponsibility: "subscription" as const,
    status: "active" as const,
    bookingId: null,
    membershipId: "seed-membership-active",
    hostAccountId: null,
    checkedInAt: hoursFromBase(-3),
    checkedOutAt: null,
  },
  {
    id: "seed-visit-booking",
    branchId: "seed-branch-main",
    personId: "seed-person-booking",
    visitType: "booking_customer" as const,
    billingResponsibility: "visitor" as const,
    status: "active" as const,
    bookingId: "seed-booking-checkedin",
    membershipId: null,
    hostAccountId: null,
    checkedInAt: hoursFromBase(-1),
    checkedOutAt: null,
  },
  {
    id: "seed-visit-guest",
    branchId: "seed-branch-main",
    personId: "seed-person-guest",
    visitType: "hosted_guest" as const,
    billingResponsibility: "host" as const,
    status: "active" as const,
    bookingId: null,
    membershipId: null,
    hostAccountId: "seed-account-host",
    checkedInAt: hoursFromBase(-2),
    checkedOutAt: null,
  },
  {
    id: "seed-visit-attendee",
    branchId: "seed-branch-main",
    personId: "seed-person-attendee",
    visitType: "event_attendee" as const,
    billingResponsibility: "event" as const,
    status: "active" as const,
    bookingId: null,
    membershipId: null,
    hostAccountId: null,
    checkedInAt: hoursFromBase(-1),
    checkedOutAt: null,
  },
  {
    id: "seed-visit-paylater",
    branchId: "seed-branch-main",
    personId: "seed-person-walkin",
    visitType: "walk_in" as const,
    billingResponsibility: "pay_later" as const,
    status: "checked_out" as const,
    bookingId: null,
    membershipId: null,
    hostAccountId: null,
    checkedInAt: hoursFromBase(-5),
    checkedOutAt: hoursFromBase(-1),
  },
  {
    id: "seed-visit-checkedout",
    branchId: "seed-branch-main",
    personId: "seed-person-member",
    visitType: "member" as const,
    billingResponsibility: "subscription" as const,
    status: "checked_out" as const,
    bookingId: null,
    membershipId: "seed-membership-active",
    hostAccountId: null,
    checkedInAt: daysFromBase(-2, 9),
    checkedOutAt: daysFromBase(-2, 17),
  },
];

export const USAGE_SESSIONS = [
  {
    id: "seed-session-walkin",
    visitId: "seed-visit-walkin",
    spaceId: "seed-space-desk-1",
    status: "active" as const,
    startedAt: hoursFromBase(-1),
    endedAt: null,
  },
  {
    id: "seed-session-member",
    visitId: "seed-visit-member",
    spaceId: "seed-space-desk-2",
    status: "active" as const,
    startedAt: hoursFromBase(-3),
    endedAt: null,
  },
  {
    id: "seed-session-booking",
    visitId: "seed-visit-booking",
    spaceId: "seed-space-meeting-room",
    status: "active" as const,
    startedAt: hoursFromBase(-1),
    endedAt: null,
  },
  {
    id: "seed-session-guest",
    visitId: "seed-visit-guest",
    spaceId: "seed-space-desk-3",
    status: "active" as const,
    startedAt: hoursFromBase(-2),
    endedAt: null,
  },
  {
    id: "seed-session-attendee",
    visitId: "seed-visit-attendee",
    spaceId: "seed-space-event-area",
    status: "active" as const,
    startedAt: hoursFromBase(-1),
    endedAt: null,
  },
  {
    id: "seed-session-ended",
    visitId: "seed-visit-paylater",
    spaceId: "seed-space-desk-3",
    status: "ended" as const,
    startedAt: hoursFromBase(-5),
    endedAt: hoursFromBase(-1),
  },
  {
    id: "seed-session-yesterday",
    visitId: "seed-visit-checkedout",
    spaceId: "seed-space-desk-1",
    status: "ended" as const,
    startedAt: daysFromBase(-2, 9),
    endedAt: daysFromBase(-2, 17),
  },
];

export const HOSTED_GUEST_LINKS = [
  {
    id: "seed-hostlink-guest",
    visitId: "seed-visit-guest",
    hostAccountId: "seed-account-host",
    guestPersonId: "seed-person-guest",
    responsibility: "host" as const,
  },
];

export const EVENTS = [
  {
    id: "seed-event-workshop",
    branchId: "seed-branch-main",
    hostAccountId: "seed-account-host",
    spaceId: "seed-space-event-area",
    name: "Tech Meetup March",
    status: "in_progress" as const,
    startsAt: hoursFromBase(-1),
    endsAt: hoursFromBase(2),
    settlementMode: "host_account",
  },
];

export const EVENT_ATTENDEES = [
  {
    id: "seed-attendee-1",
    eventId: "seed-event-workshop",
    personId: "seed-person-attendee",
    visitId: "seed-visit-attendee",
    status: "checked_in" as const,
    checkedInAt: hoursFromBase(-1),
  },
];

export const CATALOG_ITEMS = [
  {
    id: "seed-item-water",
    name: "Bottled Water (500ml)",
    kind: "product" as const,
    defaultPriceCents: 1000,
    currency: "EGP",
    trackStock: true,
  },
  {
    id: "seed-item-coffee",
    name: "Espresso",
    kind: "product" as const,
    defaultPriceCents: 2500,
    currency: "EGP",
    trackStock: true,
  },
  {
    id: "seed-item-printing",
    name: "Black & White Print (per page)",
    kind: "service" as const,
    defaultPriceCents: 200,
    currency: "EGP",
    trackStock: false,
  },
  {
    id: "seed-item-snack",
    name: "Protein Bar",
    kind: "product" as const,
    defaultPriceCents: 3500,
    currency: "EGP",
    trackStock: true,
  },
  {
    id: "seed-item-meeting-hour",
    name: "Meeting Room (per hour)",
    kind: "service" as const,
    defaultPriceCents: 20000,
    currency: "EGP",
    trackStock: false,
  },
];

export const CHARGES = [
  {
    id: "seed-charge-product",
    visitId: "seed-visit-walkin",
    usageSessionId: null,
    eventId: null,
    hostAccountId: null,
    invoiceId: null,
    type: "product" as const,
    label: "Bottled Water (500ml)",
    quantity: 2,
    amountCents: 2000,
    currency: "EGP",
    billingResponsibility: "visitor" as const,
    reason: null,
  },
  {
    id: "seed-charge-service",
    visitId: "seed-visit-booking",
    usageSessionId: null,
    eventId: null,
    hostAccountId: null,
    invoiceId: null,
    type: "service" as const,
    label: "Meeting Room (per hour)",
    quantity: 2,
    amountCents: 40000,
    currency: "EGP",
    billingResponsibility: "visitor" as const,
    reason: null,
  },
  {
    id: "seed-charge-complimentary",
    visitId: "seed-visit-member",
    usageSessionId: null,
    eventId: null,
    hostAccountId: null,
    invoiceId: null,
    type: "complimentary" as const,
    label: "Welcome Coffee",
    quantity: 1,
    amountCents: 0,
    currency: "EGP",
    billingResponsibility: "complimentary" as const,
    reason: "Member welcome promotion",
  },
  {
    id: "seed-charge-paylater",
    visitId: "seed-visit-paylater",
    usageSessionId: null,
    eventId: null,
    hostAccountId: null,
    invoiceId: null,
    type: "product" as const,
    label: "Bottled Water (500ml)",
    quantity: 1,
    amountCents: 1000,
    currency: "EGP",
    billingResponsibility: "pay_later" as const,
    reason: "Left wallet at home - pay later",
  },
  {
    id: "seed-charge-host-visit",
    visitId: "seed-visit-guest",
    usageSessionId: null,
    eventId: null,
    hostAccountId: null,
    invoiceId: null,
    type: "fee" as const,
    label: "Day Pass - Hosted Guest",
    quantity: 1,
    amountCents: 20000,
    currency: "EGP",
    billingResponsibility: "host" as const,
    reason: "Hosted guest day pass (host billed)",
  },
  {
    id: "seed-charge-event",
    visitId: null,
    usageSessionId: null,
    eventId: "seed-event-workshop",
    hostAccountId: null,
    invoiceId: null,
    type: "fee" as const,
    label: "Event Space Fee",
    quantity: 1,
    amountCents: 50000,
    currency: "EGP",
    billingResponsibility: "event" as const,
    reason: "Event space usage",
  },
  {
    id: "seed-charge-discount",
    visitId: "seed-visit-booking",
    usageSessionId: null,
    eventId: null,
    hostAccountId: null,
    invoiceId: null,
    type: "discount" as const,
    label: "Early Bird Discount",
    quantity: 1,
    amountCents: -5000,
    currency: "EGP",
    billingResponsibility: "visitor" as const,
    reason: "10% early booking discount",
  },
  {
    id: "seed-charge-print-service",
    visitId: "seed-visit-walkin",
    usageSessionId: null,
    eventId: null,
    hostAccountId: null,
    invoiceId: null,
    type: "service" as const,
    label: "Black & White Prints",
    quantity: 10,
    amountCents: 2000,
    currency: "EGP",
    billingResponsibility: "visitor" as const,
    reason: null,
  },
];

export const INVOICES = [
  {
    id: "seed-invoice-paid",
    billToPersonId: "seed-person-walkin",
    billToAccountId: null,
    status: "paid" as const,
    subtotalCents: 4000,
    discountCents: 0,
    taxCents: 0,
    totalCents: 4000,
    currency: "EGP",
    finalizedAt: hoursFromBase(-4),
  },
  {
    id: "seed-invoice-unpaid",
    billToPersonId: "seed-person-walkin",
    billToAccountId: null,
    status: "draft" as const,
    subtotalCents: 1000,
    discountCents: 0,
    taxCents: 0,
    totalCents: 1000,
    currency: "EGP",
    finalizedAt: null,
  },
  {
    id: "seed-invoice-booking",
    billToPersonId: "seed-person-booking",
    billToAccountId: null,
    status: "draft" as const,
    subtotalCents: 35000,
    discountCents: 5000,
    taxCents: 0,
    totalCents: 30000,
    currency: "EGP",
    finalizedAt: null,
  },
];

export const INVOICE_ITEMS = [
  {
    id: "seed-item-invoice-paid",
    invoiceId: "seed-invoice-paid",
    chargeId: "seed-charge-product",
    label: "Bottled Water (500ml) x2",
    amountCents: 2000,
  },
  {
    id: "seed-item-invoice-paid-2",
    invoiceId: "seed-invoice-paid",
    chargeId: "seed-charge-print-service",
    label: "Black & White Prints x10",
    amountCents: 2000,
  },
  {
    id: "seed-item-invoice-unpaid",
    invoiceId: "seed-invoice-unpaid",
    chargeId: "seed-charge-paylater",
    label: "Bottled Water (500ml)",
    amountCents: 1000,
  },
  {
    id: "seed-item-invoice-booking-1",
    invoiceId: "seed-invoice-booking",
    chargeId: "seed-charge-service",
    label: "Meeting Room (per hour) x2",
    amountCents: 40000,
  },
  {
    id: "seed-item-invoice-booking-discount",
    invoiceId: "seed-invoice-booking",
    chargeId: "seed-charge-discount",
    label: "Early Bird Discount",
    amountCents: -5000,
  },
];

export const PAYMENTS = [
  {
    id: "seed-payment-cash",
    invoiceId: "seed-invoice-paid",
    shiftId: "seed-shift-open",
    method: "cash" as const,
    status: "recorded" as const,
    amountCents: 4000,
    currency: "EGP",
    reference: "Cash payment at reception",
  },
];

export const SHIFTS = [
  {
    id: "seed-shift-open",
    branchId: "seed-branch-main",
    openedByUserId: "seed-user-cashier",
    closedByUserId: null,
    status: "open" as const,
    openedAt: hoursFromBase(-8),
    closedAt: null,
    expectedCashCents: 0,
    actualCashCents: null,
    currency: "EGP",
    notes: "Morning shift",
  },
  {
    id: "seed-shift-closed",
    branchId: "seed-branch-main",
    openedByUserId: "seed-user-cashier",
    closedByUserId: "seed-user-cashier",
    status: "closed" as const,
    openedAt: daysFromBase(-1, 8),
    closedAt: daysFromBase(-1, 16),
    expectedCashCents: 15000,
    actualCashCents: 14200,
    currency: "EGP",
    notes: "Yesterday's shift - 800 EGP discrepancy",
  },
];

export const INVENTORY_MOVEMENTS = [
  {
    id: "seed-movement-water-in",
    catalogItemId: "seed-item-water",
    quantity: 48,
    movementType: "in" as const,
    reason: "Stock replenishment",
  },
  {
    id: "seed-movement-water-out",
    catalogItemId: "seed-item-water",
    quantity: 12,
    movementType: "out" as const,
    reason: "Sales consumption",
  },
  {
    id: "seed-movement-snack-in",
    catalogItemId: "seed-item-snack",
    quantity: 24,
    movementType: "in" as const,
    reason: "Stock replenishment",
  },
  {
    id: "seed-movement-coffee-out",
    catalogItemId: "seed-item-coffee",
    quantity: 30,
    movementType: "out" as const,
    reason: "Sales consumption",
  },
];

export const CLEANING_TASKS = [
  {
    id: "seed-cleaning-office",
    spaceId: "seed-space-private-office",
    status: "open" as const,
    reason: "Scheduled daily cleaning",
    assignedToUserId: "seed-user-cleaner",
  },
  {
    id: "seed-cleaning-meeting",
    spaceId: "seed-space-meeting-room",
    status: "in_progress" as const,
    reason: "Post-meeting cleanup needed",
    assignedToUserId: "seed-user-cleaner",
  },
  {
    id: "seed-cleaning-event",
    spaceId: "seed-space-event-area",
    status: "open" as const,
    reason: "Event teardown cleaning",
    assignedToUserId: null,
  },
];

export const MAINTENANCE_TICKETS = [
  {
    id: "seed-maintenance-ac",
    spaceId: "seed-space-maintenance-room",
    status: "open" as const,
    severity: "blocking" as const,
    title: "AC unit not cooling",
    description: "AC in storage room blowing hot air. Needs urgent repair.",
    assignedToUserId: "seed-user-maintenance",
  },
  {
    id: "seed-maintenance-light",
    spaceId: "seed-space-blocked-desk",
    status: "in_progress" as const,
    severity: "low" as const,
    title: "Replace flickering light",
    description: "Desk C1 overhead light flickers intermittently.",
    assignedToUserId: "seed-user-maintenance",
  },
];

export const APPROVAL_REQUESTS = [
  {
    id: "seed-approval-discount",
    branchId: "seed-branch-main",
    requestedByUserId: "seed-user-cashier",
    reviewedByUserId: null,
    action: "discount.override",
    targetType: "charge",
    targetId: "seed-charge-discount",
    status: "pending" as const,
    reason: "Discount exceeds cashier threshold",
    reviewedAt: null,
  },
  {
    id: "seed-approval-complimentary",
    branchId: "seed-branch-main",
    requestedByUserId: "seed-user-cashier",
    reviewedByUserId: "seed-user-manager",
    action: "complimentary.approve",
    targetType: "charge",
    targetId: "seed-charge-complimentary",
    status: "approved" as const,
    reason: "Member welcome promotion approved by manager",
    reviewedAt: hoursFromBase(-2),
  },
];

export const AUDIT_LOGS = [
  {
    id: "seed-audit-visit-walkin",
    branchId: "seed-branch-main",
    actorUserId: "seed-user-cashier",
    action: "visit.create",
    entityType: "visit",
    entityId: "seed-visit-walkin",
    metadata: JSON.stringify({ visitType: "walk_in", personName: "Ahmed Farouk" }),
  },
  {
    id: "seed-audit-visit-member",
    branchId: "seed-branch-main",
    actorUserId: "seed-user-cashier",
    action: "visit.create",
    entityType: "visit",
    entityId: "seed-visit-member",
    metadata: JSON.stringify({ visitType: "member", personName: "Sara Mahmoud" }),
  },
  {
    id: "seed-audit-charge-complimentary",
    branchId: "seed-branch-main",
    actorUserId: "seed-user-cashier",
    action: "charge.add",
    entityType: "charge",
    entityId: "seed-charge-complimentary",
    metadata: JSON.stringify({ type: "complimentary", reason: "Member welcome promotion" }),
  },
  {
    id: "seed-audit-checkout-paylater",
    branchId: "seed-branch-main",
    actorUserId: "seed-user-cashier",
    action: "checkout.complete",
    entityType: "visit",
    entityId: "seed-visit-paylater",
    metadata: JSON.stringify({ billingResponsibility: "pay_later", totalCents: 1000 }),
  },
];
