export interface InventoryItem {
  id: string;
  nameAr: string;
  nameEn: string;
  category: "beverages" | "snacks" | "meals";
  defaultPrice: number;
  unit: string;
  icon: string;
}

export const INVENTORY_ITEMS: InventoryItem[] = [
  // المشروبات الساخنة
  {
    id: "tea",
    nameAr: "شاي",
    nameEn: "Tea",
    category: "beverages",
    defaultPrice: 5,
    unit: "كوب",
    icon: "☕",
  },
  {
    id: "coffee",
    nameAr: "قهوة",
    nameEn: "Coffee",
    category: "beverages",
    defaultPrice: 10,
    unit: "كوب",
    icon: "☕",
  },
  {
    id: "nescafe",
    nameAr: "نسكافيه",
    nameEn: "Nescafe",
    category: "beverages",
    defaultPrice: 8,
    unit: "كوب",
    icon: "☕",
  },
  {
    id: "hot_chocolate",
    nameAr: "شوكولاتة ساخنة",
    nameEn: "Hot Chocolate",
    category: "beverages",
    defaultPrice: 12,
    unit: "كوب",
    icon: "🍫",
  },
  {
    id: "sahlab",
    nameAr: "سحلب",
    nameEn: "Sahlab",
    category: "beverages",
    defaultPrice: 15,
    unit: "كوب",
    icon: "🥛",
  },

  // المشروبات الباردة
  {
    id: "pepsi",
    nameAr: "بيبسي",
    nameEn: "Pepsi",
    category: "beverages",
    defaultPrice: 8,
    unit: "علبة",
    icon: "🥤",
  },
  {
    id: "coca_cola",
    nameAr: "كوكاكولا",
    nameEn: "Coca Cola",
    category: "beverages",
    defaultPrice: 8,
    unit: "علبة",
    icon: "🥤",
  },
  {
    id: "sprite",
    nameAr: "سبرايت",
    nameEn: "Sprite",
    category: "beverages",
    defaultPrice: 8,
    unit: "علبة",
    icon: "🥤",
  },
  {
    id: "fanta",
    nameAr: "فانتا",
    nameEn: "Fanta",
    category: "beverages",
    defaultPrice: 8,
    unit: "علبة",
    icon: "🥤",
  },
  {
    id: "water",
    nameAr: "مياه",
    nameEn: "Water",
    category: "beverages",
    defaultPrice: 3,
    unit: "زجاجة",
    icon: "💧",
  },
  {
    id: "juice_orange",
    nameAr: "عصير برتقال",
    nameEn: "Orange Juice",
    category: "beverages",
    defaultPrice: 12,
    unit: "كوب",
    icon: "🍊",
  },
  {
    id: "juice_mango",
    nameAr: "عصير مانجو",
    nameEn: "Mango Juice",
    category: "beverages",
    defaultPrice: 15,
    unit: "كوب",
    icon: "🥭",
  },
  {
    id: "juice_apple",
    nameAr: "عصير تفاح",
    nameEn: "Apple Juice",
    category: "beverages",
    defaultPrice: 12,
    unit: "كوب",
    icon: "🍎",
  },
  {
    id: "lemonade",
    nameAr: "ليمونادة",
    nameEn: "Lemonade",
    category: "beverages",
    defaultPrice: 10,
    unit: "كوب",
    icon: "🍋",
  },
  {
    id: "iced_coffee",
    nameAr: "قهوة مثلجة",
    nameEn: "Iced Coffee",
    category: "beverages",
    defaultPrice: 15,
    unit: "كوب",
    icon: "🧊",
  },

  // السناكس والحلويات
  {
    id: "chips_lays",
    nameAr: "شيبسي ليز",
    nameEn: "Lays Chips",
    category: "snacks",
    defaultPrice: 8,
    unit: "كيس",
    icon: "🍟",
  },
  {
    id: "chips_chipsy",
    nameAr: "شيبسي",
    nameEn: "Chipsy",
    category: "snacks",
    defaultPrice: 6,
    unit: "كيس",
    icon: "🍟",
  },
  {
    id: "biscuits_oreo",
    nameAr: "بسكوت أوريو",
    nameEn: "Oreo Biscuits",
    category: "snacks",
    defaultPrice: 10,
    unit: "علبة",
    icon: "🍪",
  },
  {
    id: "biscuits_digestive",
    nameAr: "بسكوت دايجستف",
    nameEn: "Digestive Biscuits",
    category: "snacks",
    defaultPrice: 12,
    unit: "علبة",
    icon: "🍪",
  },
  {
    id: "chocolate_galaxy",
    nameAr: "شوكولاتة جالاكسي",
    nameEn: "Galaxy Chocolate",
    category: "snacks",
    defaultPrice: 15,
    unit: "قطعة",
    icon: "🍫",
  },
  {
    id: "chocolate_kitkat",
    nameAr: "كيت كات",
    nameEn: "Kit Kat",
    category: "snacks",
    defaultPrice: 8,
    unit: "قطعة",
    icon: "🍫",
  },
  {
    id: "nuts_mixed",
    nameAr: "مكسرات مشكلة",
    nameEn: "Mixed Nuts",
    category: "snacks",
    defaultPrice: 20,
    unit: "كيس",
    icon: "🥜",
  },
  {
    id: "popcorn",
    nameAr: "فشار",
    nameEn: "Popcorn",
    category: "snacks",
    defaultPrice: 10,
    unit: "كيس",
    icon: "🍿",
  },

  // الوجبات السريعة
  {
    id: "indomie",
    nameAr: "إندومي",
    nameEn: "Indomie",
    category: "meals",
    defaultPrice: 8,
    unit: "كيس",
    icon: "🍜",
  },
  {
    id: "sandwich_cheese",
    nameAr: "ساندوتش جبنة",
    nameEn: "Cheese Sandwich",
    category: "meals",
    defaultPrice: 15,
    unit: "قطعة",
    icon: "🥪",
  },
  {
    id: "sandwich_tuna",
    nameAr: "ساندوتش تونة",
    nameEn: "Tuna Sandwich",
    category: "meals",
    defaultPrice: 20,
    unit: "قطعة",
    icon: "🥪",
  },
  {
    id: "toast",
    nameAr: "توست",
    nameEn: "Toast",
    category: "meals",
    defaultPrice: 12,
    unit: "قطعة",
    icon: "🍞",
  },
  {
    id: "croissant",
    nameAr: "كرواسون",
    nameEn: "Croissant",
    category: "meals",
    defaultPrice: 18,
    unit: "قطعة",
    icon: "🥐",
  },
  {
    id: "pizza_slice",
    nameAr: "قطعة بيتزا",
    nameEn: "Pizza Slice",
    category: "meals",
    defaultPrice: 25,
    unit: "قطعة",
    icon: "🍕",
  },
];

export const INVENTORY_CATEGORIES = {
  beverages: {
    nameAr: "المشروبات",
    nameEn: "Beverages",
    icon: "🥤",
  },
  snacks: {
    nameAr: "السناكس",
    nameEn: "Snacks",
    icon: "🍿",
  },
  meals: {
    nameAr: "الوجبات",
    nameEn: "Meals",
    icon: "🍽️",
  },
} as const;
