// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCustomer(arg1) {
  return window['go']['main']['App']['AddCustomer'](arg1);
}

export function AddInventory(arg1) {
  return window['go']['main']['App']['AddInventory'](arg1);
}

export function AddResource(arg1) {
  return window['go']['main']['App']['AddResource'](arg1);
}

export function AddSessionInventory(arg1, arg2) {
  return window['go']['main']['App']['AddSessionInventory'](arg1, arg2);
}

export function AddSubscription(arg1) {
  return window['go']['main']['App']['AddSubscription'](arg1);
}

export function AdjustInventoryQuantity(arg1, arg2) {
  return window['go']['main']['App']['AdjustInventoryQuantity'](arg1, arg2);
}

export function CancelSubscription(arg1) {
  return window['go']['main']['App']['CancelSubscription'](arg1);
}

export function ChangeSubscriptionPlan(arg1, arg2) {
  return window['go']['main']['App']['ChangeSubscriptionPlan'](arg1, arg2);
}

export function CheckCustomerDuplicate(arg1, arg2) {
  return window['go']['main']['App']['CheckCustomerDuplicate'](arg1, arg2);
}

export function DeactivateSubscription(arg1) {
  return window['go']['main']['App']['DeactivateSubscription'](arg1);
}

export function DeleteCustomer(arg1) {
  return window['go']['main']['App']['DeleteCustomer'](arg1);
}

export function DeleteInventory(arg1) {
  return window['go']['main']['App']['DeleteInventory'](arg1);
}

export function DeleteResource(arg1) {
  return window['go']['main']['App']['DeleteResource'](arg1);
}

export function DeleteSubscription(arg1) {
  return window['go']['main']['App']['DeleteSubscription'](arg1);
}

export function EndSession(arg1) {
  return window['go']['main']['App']['EndSession'](arg1);
}

export function GetActiveSessions() {
  return window['go']['main']['App']['GetActiveSessions']();
}

export function GetCustomers() {
  return window['go']['main']['App']['GetCustomers']();
}

export function GetCustomersPaginated(arg1) {
  return window['go']['main']['App']['GetCustomersPaginated'](arg1);
}

export function GetDashboardMetrics() {
  return window['go']['main']['App']['GetDashboardMetrics']();
}

export function GetInventory() {
  return window['go']['main']['App']['GetInventory']();
}

export function GetInvoices() {
  return window['go']['main']['App']['GetInvoices']();
}

export function GetInvoicesPaginated(arg1, arg2) {
  return window['go']['main']['App']['GetInvoicesPaginated'](arg1, arg2);
}

export function GetResources() {
  return window['go']['main']['App']['GetResources']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetSubscriptions() {
  return window['go']['main']['App']['GetSubscriptions']();
}

export function ProcessBulkPayment(arg1) {
  return window['go']['main']['App']['ProcessBulkPayment'](arg1);
}

export function ProcessPayment(arg1) {
  return window['go']['main']['App']['ProcessPayment'](arg1);
}

export function ReactivateSubscription(arg1) {
  return window['go']['main']['App']['ReactivateSubscription'](arg1);
}

export function RemoveSessionInventory(arg1, arg2) {
  return window['go']['main']['App']['RemoveSessionInventory'](arg1, arg2);
}

export function ResetAndSeedDatabase() {
  return window['go']['main']['App']['ResetAndSeedDatabase']();
}

export function SeedDatabase() {
  return window['go']['main']['App']['SeedDatabase']();
}

export function SeedLargeDataset() {
  return window['go']['main']['App']['SeedLargeDataset']();
}

export function StartSession(arg1, arg2) {
  return window['go']['main']['App']['StartSession'](arg1, arg2);
}

export function UpdateCustomer(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomer'](arg1, arg2);
}

export function UpdateInventory(arg1, arg2) {
  return window['go']['main']['App']['UpdateInventory'](arg1, arg2);
}

export function UpdateResource(arg1, arg2) {
  return window['go']['main']['App']['UpdateResource'](arg1, arg2);
}

export function UpdateSessionInventory(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateSessionInventory'](arg1, arg2, arg3);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateSubscription(arg1, arg2) {
  return window['go']['main']['App']['UpdateSubscription'](arg1, arg2);
}
