// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function AddCustomer(arg1:models.Customer):Promise<void>;

export function AddInventory(arg1:models.InventoryItem):Promise<void>;

export function AddResource(arg1:models.Resource):Promise<void>;

export function AddSessionInventory(arg1:string,arg2:models.SessionInventoryInput):Promise<void>;

export function AddSubscription(arg1:main.AddSubscriptionData):Promise<void>;

export function AdjustInventoryQuantity(arg1:string,arg2:number):Promise<void>;

export function CancelSubscription(arg1:string):Promise<void>;

export function ChangeSubscriptionPlan(arg1:string,arg2:string):Promise<void>;

export function CheckCustomerDuplicate(arg1:string,arg2:string):Promise<models.Customer>;

export function DeactivateSubscription(arg1:string):Promise<void>;

export function DeleteCustomer(arg1:string):Promise<void>;

export function DeleteInventory(arg1:string):Promise<void>;

export function DeleteResource(arg1:string):Promise<void>;

export function DeleteSubscription(arg1:string):Promise<void>;

export function EndSession(arg1:string):Promise<string>;

export function GetActiveSessions():Promise<Array<models.Session>>;

export function GetCustomers():Promise<Array<models.Customer>>;

export function GetDashboardMetrics():Promise<models.DashboardMetrics>;

export function GetInventory():Promise<Array<models.InventoryItem>>;

export function GetInvoices():Promise<Array<models.Invoice>>;

export function GetResources():Promise<Array<models.Resource>>;

export function GetSettings():Promise<models.Settings>;

export function GetSubscriptions():Promise<Array<models.Subscription>>;

export function ProcessBulkPayment(arg1:main.BulkPaymentData):Promise<void>;

export function ProcessPayment(arg1:main.ProcessPaymentData):Promise<void>;

export function ReactivateSubscription(arg1:string):Promise<void>;

export function RemoveSessionInventory(arg1:string,arg2:string):Promise<void>;

export function ResetAndSeedDatabase():Promise<string>;

export function SeedDatabase():Promise<string>;

export function StartSession(arg1:string,arg2:string):Promise<void>;

export function UpdateCustomer(arg1:string,arg2:models.Customer):Promise<void>;

export function UpdateInventory(arg1:string,arg2:models.InventoryItem):Promise<void>;

export function UpdateResource(arg1:string,arg2:models.Resource):Promise<void>;

export function UpdateSessionInventory(arg1:string,arg2:string,arg3:number):Promise<void>;

export function UpdateSettings(arg1:models.Settings):Promise<void>;

export function UpdateSubscription(arg1:string,arg2:models.Subscription):Promise<void>;
